### ISSUE TITLE
The command 'clear' doesn't work on windows.

### ISSUE THREAD

**Issue by masoudd** [liviu-/ding#3]
![ding](https://cloud.githubusercontent.com/assets/828670/19023249/b43c92ec-88f6-11e6-81eb-99669fee33b7.png)

**Comment by liviu-** [comment]
Wow do you get a sound on Windows at all? I haven't really done much effort to support Windows as I don't have an environment to test it on right now (maybe I should've been more clear in the README.md, sorry), and to my understanding the Windows beeping is a bit more complicated (i.e. must be done via their beeping API / Python's `winsound`).

The `clear` part is easily fixed by replacing `os.system('clear')` [here](https://github.com/liviu-/ding/blob/develop/ding/ding.py#L85) with `os.system('cls' if os.name == 'nt' else 'clear')`, but I thought that the beep doesn't work at all on Window. Do you get any sound when the countdown finishes?

**Comment by masoudd** [comment]
It does sound a beep. More like 3 very close consecutive beeps.

**Comment by liviu-** [comment]
Oh that's great -- I'll try to push a patch today and release a new version asap

**Comment by liviu-** [comment]
I pushed an update (1.2.0) to fix the issue -- it should work if you do

```
$ pip install --upgrade ding-ding
```

Many thanks for reporting the issue, and please let me know if the problem persists!
